const products = [
    /* ---------------- ELECTRONICS - PHONES (10+ Items) ---------------- */
    {
        id: 1,
        name: "Apple iPhone 15 Pro (128 GB) - Blue Titanium",
        category: "mobiles",
        subCategory: "phones",
        price: 129990,
        rating: 4.8,
        reviews: 25000,
        image: "https://i.pinimg.com/736x/5f/11/2c/5f112c7a5d55b72eb012319f884347fa.jpg",
        description: "Experience the ultimate iPhone with titanium design and A17 Pro chip.",
        badge: "Bestseller"
    },
    {
        id: 2,
        name: "Samsung Galaxy S24 Ultra (512GB) - Titanium Gray",
        category: "mobiles",
        subCategory: "phones",
        price: 119999,
        rating: 4.7,
        reviews: 18000,
        image: "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?auto=format&fit=crop&q=80&w=400&h=400",
        description: "AI-powered camera and pro-grade performance for unparalleled creativity.",
        badge: "Trending"
    },
    {
        id: 3,
        name: "Google Pixel 8 Pro - Porcelain",
        category: "mobiles",
        subCategory: "phones",
        price: 106990,
        rating: 4.5,
        reviews: 5400,
        image: "https://i.pinimg.com/1200x/37/1f/bc/371fbc0e6566beac9803cbb8a8a979ff.jpg",
        description: "The most advanced Pixel yet, with a refined design and powerful Google AI.",
        badge: ""
    },
    {
        id: 4,
        name: "OnePlus 12 (16GB RAM, 512GB Storage) - Flowy Emerald",
        category: "mobiles",
        subCategory: "phones",
        price: 69999,
        rating: 4.6,
        reviews: 12000,
        image: "https://i.pinimg.com/474x/77/d3/ca/77d3cae4f9b677c5b2747bf110d609bb.jpg",
        description: "Fast and smooth performance with revolutionary Hasselblad camera.",
        badge: "Great Value"
    },
    {
        id: 5,
        name: "Nothing Phone (2) - Dark Gray",
        category: "mobiles",
        subCategory: "phones",
        price: 44999,
        rating: 4.4,
        reviews: 3200,
        image: "https://images.unsplash.com/photo-1621330396173-e41b1cafd17f?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Unique Glyph interface and powerful Snapdragon 8+ Gen 1 processor.",
        badge: "Innovative"
    },
    {
        id: 6,
        name: "Xiaomi 14 Ultra - Black",
        category: "mobiles",
        subCategory: "phones",
        price: 99999,
        rating: 4.7,
        reviews: 800,
        image: "https://i.pinimg.com/736x/e0/bf/be/e0bfbe214ad2b0a70a0c0af30b7b486c.jpg",
        description: "Leica optics and unparalleled camera performance for photographers.",
        badge: "New Release"
    },
    {
        id: 7,
        name: "Motorola Edge 50 Pro - Luxe Lavender",
        category: "mobiles",
        subCategory: "phones",
        price: 35999,
        rating: 4.3,
        reviews: 2100,
        image: "https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Sleek design with 144Hz curved display and 125W fast charging.",
        badge: "Fastest Charging"
    },
    {
        id: 8,
        name: "Realme 12 Pro+ 5G - Submarine Blue",
        category: "mobiles",
        subCategory: "phones",
        price: 29999,
        rating: 4.4,
        reviews: 4500,
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Telephoto periscope lens in a luxury watch inspired design.",
        badge: "Style Leader"
    },
    {
        id: 9,
        name: "Apple iPhone 13 (128GB) - Midnight",
        category: "mobiles",
        subCategory: "phones",
        price: 48999,
        rating: 4.7,
        reviews: 180000,
        image: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=400&h=400&fit=crop",
        description: "The most popular iPhone with stunning OLED display and A15 Bionic.",
        badge: "Top Seller"
    },
    {
        id: 10,
        name: "Vivo V30 Pro - Andaman Blue",
        category: "mobiles",
        subCategory: "phones",
        price: 41999,
        rating: 4.5,
        reviews: 1200,
        image: "https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=400&h=400&fit=crop",
        description: "Zeiss Professional Portrait Camera and ultra-slim design.",
        badge: "Portrait Master"
    },

    /* ---------------- ELECTRONICS - LAPTOPS & AUDIO (10+ Items) ---------------- */
    {
        id: 11,
        name: "Apple MacBook Pro M3 (14-inch) - Silver",
        category: "electronics",
        subCategory: "laptops",
        price: 154990,
        rating: 4.9,
        reviews: 3200,
        image: "https://i.pinimg.com/736x/cb/fd/1c/cbfd1c6a2db6bdb1dd8b72020388013d.jpg",
        description: "Mind-blowing performance for pros with the M3 chip and liquid retina display.",
        badge: "Premium Choice"
    },
    {
        id: 12,
        name: "Dell XPS 13 (Intel Core i7, 16GB RAM) - Platinum",
        category: "electronics",
        subCategory: "laptops",
        price: 112000,
        rating: 4.5,
        reviews: 4500,
        image: "https://i.pinimg.com/1200x/e0/a0/55/e0a055dd1c874856c7188142220ef886.jpg",
        description: "Ultra-portable performance with an edge-to-edge InfinityEdge display.",
        badge: "Thin & Light"
    },
    {
        id: 13,
        name: "HP Spectre x360 2-in-1 Laptop - Nightfall Black",
        category: "electronics",
        subCategory: "laptops",
        price: 125000,
        rating: 4.4,
        reviews: 2100,
        image: "https://i.pinimg.com/1200x/29/c7/98/29c798c496d6a899a47b9501b3572a76.jpg",
        description: "Versatile 2-in-1 design with stunning 4K OLED display and long battery life.",
        badge: "Versatile"
    },
    {
        id: 14,
        name: "ASUS ROG Zephyrus G14 - Eclipse Gray",
        category: "electronics",
        subCategory: "laptops",
        price: 139990,
        rating: 4.8,
        reviews: 1200,
        image: "https://i.pinimg.com/736x/8d/4e/6d/8d4e6da4a23cc557c60c8cd386bf3694.jpg",
        description: "The world's most powerful 14-inch gaming laptop with Ryzen 9 and RTX 40-series.",
        badge: "Gamer's Choice"
    },
    {
        id: 15,
        name: "Sony WH-1000XM5 Wireless Headphones - Black",
        category: "electronics",
        subCategory: "audio",
        price: 29990,
        rating: 4.7,
        reviews: 15000,
        image: "https://i.pinimg.com/1200x/08/25/4c/08254ce0f681476675c70cedff46c6bf.jpg",
        description: "Industry-leading noise cancellation and breathtaking sound quality.",
        badge: "Bestseller"
    },
    {
        id: 16,
        name: "Logitech MX Master 3S Wireless Mouse",
        category: "electronics",
        subCategory: "accessories",
        price: 10495,
        rating: 4.8,
        reviews: 8900,
        image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop",
        description: "The ultimate productivity mouse with MagSpeed scrolling and 8K DPI.",
        badge: "Pro Choice"
    },
    {
        id: 17,
        name: "Apple iPad Air (M2, 11-inch) - Space Gray",
        category: "electronics",
        subCategory: "tablets",
        price: 59900,
        rating: 4.8,
        reviews: 4200,
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
        description: "Powerful iPad with M2 chip and support for Apple Pencil Pro.",
        badge: "Trending"
    },
    {
        id: 18,
        name: "Microsoft Surface Pro 9 - Sapphire",
        category: "electronics",
        subCategory: "laptops",
        price: 105000,
        rating: 4.4,
        reviews: 1200,
        image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
        description: "The tablet that can replace your laptop, now with 12th Gen Intel cores.",
        badge: "Portable Power"
    },
    {
        id: 19,
        name: "Bose QuietComfort Earbuds II - Soapstone",
        category: "electronics",
        subCategory: "audio",
        price: 24900,
        rating: 4.6,
        reviews: 3200,
        image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop",
        description: "World's best noise cancellation and personalized sound.",
        badge: "Top Rated"
    },
    {
        id: 20,
        name: "Samsung Odyssey G7 27-inch Gaming Monitor",
        category: "electronics",
        subCategory: "accessories",
        price: 45000,
        rating: 4.7,
        reviews: 5400,
        image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop",
        description: "Unmatched immersion with 1000R curvature and 240Hz refresh rate.",
        badge: "Pro Gamer"
    },

    /* ---------------- FASHION - MEN (10+ Items) ---------------- */
    {
        id: 21,
        name: "Levi's Men's 511 Slim Fit Jeans",
        category: "fashion",
        subCategory: "mens-wear",
        price: 2499,
        rating: 4.2,
        reviews: 8900,
        image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop",
        description: "A modern slim with room to move, perfect for everyday wear.",
        badge: "Bestseller"
    },
    {
        id: 22,
        name: "Tommy Hilfiger Men's Cotton Shirt",
        category: "fashion",
        subCategory: "mens-wear",
        price: 3299,
        rating: 4.3,
        reviews: 1200,
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop",
        description: "Premium cotton shirt with a tailored fit and signature brand detailing.",
        badge: "Deal of the Day"
    },
    {
        id: 23,
        name: "Adidas Originals Trefoil Hoodie",
        category: "fashion",
        subCategory: "mens-wear",
        price: 4999,
        rating: 4.5,
        reviews: 6700,
        image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=400&fit=crop",
        description: "Classic comfort meeting iconic style for the modern active man.",
        badge: "Seasonal"
    },
    {
        id: 24,
        name: "Nike Air Force 1 '07 Sneakers",
        category: "fashion",
        subCategory: "mens-shoes",
        price: 9695,
        rating: 4.8,
        reviews: 12500,
        image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop",
        description: "Radiant luxury and timeless design make this basketball icon a must-have.",
        badge: "Street Style"
    },
    {
        id: 25,
        name: "Puma Men's T7 Track Jacket",
        category: "fashion",
        subCategory: "mens-wear",
        price: 3499,
        rating: 4.2,
        reviews: 1540,
        image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop",
        description: "An archive original that continues to define retro athletic style.",
        badge: "Classic"
    },
    {
        id: 26,
        name: "U.S. Polo Assn. Men's Polo Shirt",
        category: "fashion",
        subCategory: "mens-wear",
        price: 1599,
        rating: 4.1,
        reviews: 43200,
        image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400&h=400&fit=crop",
        description: "Authentically styled gear for the sportsman and the casual dresser.",
        badge: "Budget Friendly"
    },
    {
        id: 27,
        name: "Ray-Ban Aviator Classic Sunglasses",
        category: "fashion",
        subCategory: "accessories",
        price: 9990,
        rating: 4.7,
        reviews: 5400,
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop",
        description: "The timeless silhouette that has defined effortless cool for generations.",
        badge: "Iconic"
    },
    {
        id: 28,
        name: "Casio G-Shock GA-2100 - Black Carbon",
        category: "fashion",
        subCategory: "accessories",
        price: 8995,
        rating: 4.6,
        reviews: 12000,
        image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&h=400&fit=crop",
        description: "The 'CasiOak' - super tough, super slim, and incredibly stylish.",
        badge: "Toughness"
    },
    {
        id: 29,
        name: "H&M Men's Relaxed Fit T-shirt - White",
        category: "fashion",
        subCategory: "mens-wear",
        price: 799,
        rating: 4.3,
        reviews: 8900,
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
        description: "Essential relaxed fit tee in heavy cotton jersey for a modern look.",
        badge: "Essential"
    },
    {
        id: 30,
        name: "Allen Solly Men's Slim Fit Chinos",
        category: "fashion",
        subCategory: "mens-wear",
        price: 1999,
        rating: 4.2,
        reviews: 6500,
        image: "https://i.pinimg.com/736x/56/55/f7/5655f7e70571c9b1573082e43b874788.jpg",
        description: "Versatile chinos for a sharp ensemble at work or on the weekend.",
        badge: "Formal Ready"
    },

    /* ---------------- FASHION - WOMEN (10+ Items) ---------------- */
    {
        id: 31,
        name: "Zara Women's Floral Print Midi Dress",
        category: "fashion",
        subCategory: "womens-wear",
        price: 3999,
        rating: 4.4,
        reviews: 1540,
        image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=400&fit=crop",
        description: "Elegant floral print that transitions perfectly from day to night.",
        badge: "New Arrival"
    },
    {
        id: 32,
        name: "H&M Women's Oversized Knit Sweater - Beige",
        category: "fashion",
        subCategory: "womens-wear",
        price: 2299,
        rating: 4.3,
        reviews: 3200,
        image: "https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=400&h=400&fit=crop",
        description: "Cozy and chic oversized fit, essential for layering in style.",
        badge: "Cozy Choice"
    },
    {
        id: 33,
        name: "Nike Women's Sportswear Leggings",
        category: "fashion",
        subCategory: "womens-wear",
        price: 2995,
        rating: 4.6,
        reviews: 8900,
        image: "https://i.pinimg.com/1200x/57/57/a6/5757a6fcd014352fba58c278a22a0372.jpg",
        description: "Supportive and breathable design, ideal for gym or everyday comfort.",
        badge: "Top Rated"
    },
    {
        id: 34,
        name: "Michael Kors Women's Jet Set Saffiano Handbag",
        category: "fashion",
        subCategory: "accessories",
        price: 22500,
        rating: 4.7,
        reviews: 1200,
        image: "https://i.pinimg.com/1200x/d2/9f/92/d29f92adbdb29faea4ead07d4e22212b.jpg",
        description: "Structured and sophisticated, the ultimate accessory for the modern woman.",
        badge: "Luxury"
    },
    {
        id: 35,
        name: "Mango Women's Tailored Blazer - Ivory",
        category: "fashion",
        subCategory: "womens-wear",
        price: 6999,
        rating: 4.4,
        reviews: 650,
        image: "https://i.pinimg.com/1200x/47/ff/02/47ff024f35f101ae9319c905dc475c8f.jpg",
        description: "Sharp tailoring and premium fabric for a boardroom-ready look.",
        badge: "Office Wear"
    },
    {
        id: 36,
        name: "Adidas Women's Stan Smith Sneakers",
        category: "fashion",
        subCategory: "womens-shoes",
        price: 8999,
        rating: 4.8,
        reviews: 9500,
        image: "https://i.pinimg.com/1200x/ba/0a/59/ba0a59d304d0455f0a6a2e173048ff87.jpg",
        description: "Clean, classic, and versatile white sneakers that never go out of style.",
        badge: "Street Choice"
    },
    {
        id: 37,
        name: "Levi's Women's 711 Skinny Jeans - Blue",
        category: "fashion",
        subCategory: "womens-wear",
        price: 2599,
        rating: 4.2,
        reviews: 12500,
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=400&fit=crop",
        description: "The ultimate skinny jean, designed to flatter, hold and lift.",
        badge: "Denim Leader"
    },
    {
        id: 38,
        name: "Daniel Wellington Petite Sterling Watch",
        category: "fashion",
        subCategory: "accessories",
        price: 13999,
        rating: 4.6,
        reviews: 3200,
        image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=400&h=400&fit=crop",
        description: "Minimalist design and silver mesh strap for an elegant, modern vibe.",
        badge: "Elegant"
    },
    {
        id: 39,
        name: "ONLY Women's Printed Top - Green",
        category: "fashion",
        subCategory: "womens-wear",
        price: 1299,
        rating: 4.1,
        reviews: 1500,
        image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=400&fit=crop",
        description: "Playful print and light fabric for effortless summer style.",
        badge: "Fresh"
    },
    {
        id: 40,
        name: "Birkenstock Arizona Sandals - Mocha",
        category: "fashion",
        subCategory: "womens-shoes",
        price: 7990,
        rating: 4.7,
        reviews: 8400,
        image: "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=400&h=400&fit=crop",
        description: "An iconic comfort legend that continues to define effortless summer style.",
        badge: "Comfort Icon"
    },

    /* ---------------- HOME & KITCHEN (10+ Items) ---------------- */
    {
        id: 41,
        name: "Samsung 80 cm (32 Inches) HD Smart LED TV",
        category: "home",
        subCategory: "appliances",
        price: 13990,
        rating: 4.2,
        reviews: 45000,
        image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop",
        description: "Vibrant colors and smart features for an immersive viewing experience.",
        badge: "Best Seller"
    },
    {
        id: 42,
        name: "Pigeon Amaze Plus 1.5 Litre Electric Kettle",
        category: "home",
        subCategory: "kitchen",
        price: 649,
        rating: 4.0,
        reviews: 150000,
        image: "https://i.pinimg.com/736x/cd/20/56/cd2056b02532458df516c932957ab54d.jpg",
        description: "Fast boiling and sleek design, perfect for tea, coffee, and more.",
        badge: "Super Value"
    },
    {
        id: 43,
        name: "Dyson V11 Absolute Cord-Free Vacuum Cleaner",
        category: "home",
        subCategory: "appliances",
        price: 45900,
        rating: 4.7,
        reviews: 3200,
        image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=400&h=400&fit=crop",
        description: "Powerful cleaning across all floor types with cord-free convenience.",
        badge: "High Tech"
    },
    {
        id: 44,
        name: "LG 28 Litre Convection Microwave Oven",
        category: "home",
        subCategory: "kitchen",
        price: 12490,
        rating: 4.4,
        reviews: 8900,
        image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=400&h=400&fit=crop",
        description: "Versatile cooking with convection and quartz heater technologies.",
        badge: "Kitchen Staple"
    },
    {
        id: 45,
        name: "Philips Daily Collection Air Fryer",
        category: "home",
        subCategory: "kitchen",
        price: 8999,
        rating: 4.5,
        reviews: 12500,
        image: "https://i.pinimg.com/1200x/f4/6c/c0/f46cc00158bcd950a6a03215e2ba46d2.jpg",
        description: "Healthy frying with up to 90% less fat and Rapid Air technology.",
        badge: "Healthy Choice"
    },
    {
        id: 46,
        name: "Prestige Iris 750 Watt Mixer Grinder",
        category: "home",
        subCategory: "kitchen",
        price: 3299,
        rating: 4.1,
        reviews: 54000,
        image: "https://images.unsplash.com/photo-1584286595398-a59f21d313f5?w=400&h=400&fit=crop",
        description: "Powerful 750W motor with versaatile stainless steel jars.",
        badge: "Indian Favorite"
    },
    {
        id: 47,
        name: "Milton Thermosteel 24 Hours Hot/Cold Flask",
        category: "home",
        subCategory: "kitchen",
        price: 999,
        rating: 4.3,
        reviews: 123000,
        image: "https://i.pinimg.com/736x/7a/87/04/7a87048ae621d687d290db8baf7abca7.jpg",
        description: "Uniquely designed stainless steel vacuum flask for temperature retention.",
        badge: "Durability"
    },
    {
        id: 48,
        name: "Kurl-on Pure Coir Single Size Mattress",
        category: "home",
        subCategory: "home-decor",
        price: 5499,
        rating: 4.2,
        reviews: 3200,
        image: "https://i.pinimg.com/736x/d3/88/26/d3882698389bc951dfb3830cdbdce636.jpg",
        description: "Naturally cooling and supportive coir mattress for a restful sleep.",
        badge: "Natural"
    },
    {
        id: 49,
        name: "Elica 60 cm 1200 m3/hr Filterless Auto Clean Chimney",
        category: "home",
        subCategory: "kitchen",
        price: 11990,
        rating: 4.4,
        reviews: 6500,
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=400&fit=crop",
        description: "Smoke-free kitchen with advanced motion sensor and auto-clean tech.",
        badge: "Smart Home"
    },
    {
        id: 50,
        name: "Solimo Microfibre Reversible Comforter",
        category: "home",
        subCategory: "home-decor",
        price: 1799,
        rating: 4.3,
        reviews: 21000,
        image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop",
        description: "Soft and breathable microfibre to keep you cozy during late nights.",
        badge: "Soft Touch"
    },
    /* ---------------- FRESH - GROCERIES (10+ Items) ---------------- */
    {
        id: 101,
        name: "Organic Red Delicious Apple Pack (1kg)",
        category: "fresh",
        subCategory: "produce",
        price: 180,
        rating: 4.6,
        reviews: 450,
        image: "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Freshly picked organic red apples, crisp and sweet.",
        badge: "Organic"
    },
    {
        id: 102,
        name: "Fresh Broccoli Florets (250g)",
        category: "fresh",
        subCategory: "produce",
        price: 95,
        rating: 4.8,
        reviews: 120,
        image: "https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Nutritious green broccoli florets, garden fresh.",
        badge: ""
    },
    {
        id: 103,
        name: "Premium Alphonso Mangoes (Box of 12)",
        category: "fresh",
        subCategory: "produce",
        price: 1200,
        rating: 4.9,
        reviews: 3200,
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=400&h=400",
        description: "The King of Mangoes, direct from Ratnagiri. Rich and creamy.",
        badge: "Seasonal"
    },
    {
        id: 104,
        name: "Aashirvaad Select Premium Sharbati Atta (5kg)",
        category: "fresh",
        subCategory: "pantry",
        price: 350,
        rating: 4.5,
        reviews: 12500,
        image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Highest quality wheat flour from central India for softest rotis.",
        badge: "Top Brand"
    },
    {
        id: 105,
        name: "Tata Salt - Iodized (1kg)",
        category: "fresh",
        subCategory: "pantry",
        price: 28,
        rating: 4.7,
        reviews: 89000,
        image: "https://i.pinimg.com/1200x/97/05/3c/97053c259b6db345056e590d553bb9ee.jpg",
        description: "The purest vacuum-evaporated iodized salt. Desh ka Namak.",
        badge: ""
    },
    {
        id: 106,
        name: "Amul Pasteurised Butter (500g)",
        category: "fresh",
        subCategory: "dairy",
        price: 275,
        rating: 4.8,
        reviews: 15600,
        image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Utterly Butterly Delicious. Pure milk butter.",
        badge: "Bestseller"
    },
    {
        id: 107,
        name: "Fortune Sunlite Refined Sunflower Oil (1L)",
        category: "fresh",
        subCategory: "pantry",
        price: 145,
        rating: 4.4,
        reviews: 5600,
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Light and healthy cooking oil enriched with vitamins.",
        badge: ""
    },
    {
        id: 108,
        name: "Nescafe Classic Coffee Jar (100g)",
        category: "fresh",
        subCategory: "pantry",
        price: 295,
        rating: 4.6,
        reviews: 12000,
        image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=400&h=400",
        description: "Signature coffee aroma and bold taste to start your morning.",
        badge: ""
    },
    {
        id: 109,
        name: "Saffola Gold Healthy Heart Oil (5L)",
        category: "fresh",
        subCategory: "pantry",
        price: 780,
        rating: 4.5,
        reviews: 8400,
        image: "https://i.pinimg.com/736x/ba/ff/8e/baff8e929372ed39482165d30ef0a3fa.jpg",
        description: "Blend of rice bran and sunflower oil for a healthy heart.",
        badge: "Best Value"
    },
    {
        id: 110,
        name: "Himalayan Pink Salt - Fine Grain (1kg)",
        category: "fresh",
        subCategory: "pantry",
        price: 120,
        rating: 4.7,
        reviews: 2100,
        image: "https://i.pinimg.com/1200x/71/e5/5b/71e55bb3817ab638263101015efc8207.jpg",
        description: "Unrefined mineral salt for extra flavor and health benefits.",
        badge: "Premium"
    }
];

export default products;
